name: nir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - numpy
  - pandas
  - pytorch
  - torchvision
  - xmltodict
  - spacy
  - nltk
  - textblob
  - pattern
  - lemminflect
  - optuna
